apiVersion: 1

deleteDatasources:
  - name: Tempo
    orgId: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      httpMethod: GET
    editable: true
